services:
  - type: web
    name: applyce
    runtime: python
    plan: free
    buildCommand: pip install -r REQUIREMENTS.txt && python init_db.py
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres.wqlvvfxhrufzcbmgdxid:Qwertyuiop2005zxcvbnmasdfghjkl@aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
      - key: ADZUNA_API_KEY
        value: 2493382c75cb1211cece11304eba0997
      - key: ADZUNA_APP_ID
        value: 0f396d0c
      - key: RAPIDAPI_KEY
        value: 89b90bf114msh0e973f8198f5bdfp1a7024jsne784128c9363
      - key: MAIL_SERVER
        value: smtp.zoho.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USERNAME
        value: samrudh@applyce.tech
      - key: MAIL_PASSWORD
        value: Applyce@admin2025
      - key: MAIL_DEFAULT_SENDER
        value: samrudh@applyce.tech
      - key: EMAIL_ADDRESS
        value: samrudh@applyce.tech
      - key: EMAIL_PASSWORD
        value: Applyce@admin2025
