services:
  - type: web
    name: career-recommendation
    env: python
    buildCommand: pip install -r REQUIREMENTS.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
